defmodule CosmicTest do
  use ExUnit.Case

  describe "solve/1" do
    test "returns the correct value" do
      file = """
      ...#......
      .......#..
      #.........
      ..........
      ......#...
      .#........
      .........#
      ..........
      .......#..
      #...#.....
      """

      assert Cosmic.solve(file) == 374
    end
  end
end
