defmodule CosmicTest do
  use ExUnit.Case

  describe "solve/1" do
    test "returns the correct value with an expansion of 10" do
      file = """
      ...#......
      .......#..
      #.........
      ..........
      ......#...
      .#........
      .........#
      ..........
      .......#..
      #...#.....
      """

      assert Cosmic.solve(file, 10) == 1030
    end

    test "returns the correct value with an expansion of 100" do
      file = """
      ...#......
      .......#..
      #.........
      ..........
      ......#...
      .#........
      .........#
      ..........
      .......#..
      #...#.....
      """

      assert Cosmic.solve(file, 100) == 8410
    end
  end
end
